# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0043_add_max_docker_image_size_for_challenge'),
        ('accounts', '0003_remove_affiliation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteUserToChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=200)),
                ('invitation_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], db_index=True, max_length=30)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenges.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_user_to_challenge',
            },
        ),
    ]
